name: 天翼云签到

on:
  workflow_dispatch:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]
  schedule:
    - cron: 0 2,14 * * *

jobs:
  check-in:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3
            
    - name: "进入文件夹"
      run: |
        cd 189cloud
        
    - name: "安装依赖包"
      run: |
        cd 189cloud
        pip3 install -r requirements.txt
        
    - name: "运行 天翼云签到"
      run: |
        user='${{ secrets.CLOUD_189_USER }}'
        pwd='${{ secrets.CLOUD_189_PWD }}'
        
        user_list=()
        pwd_list=()
        IFS=" "
        for u in ${user[*]}
        do
        user_list[${#user_list[*]}]=${u}
        done
        for p in ${pwd[*]}
        do
        pwd_list[${#pwd_list[*]}]=${p}
        done
        user_num=${#user_list[*]}
        pwd_num=${#pwd_list[*]}
        if [ $user_num != $pwd_num ];then
        echo "账号和密码个数不对应"
        exit 1
        else
        echo "共有 $user_num 个账号，即将开始签到"
        fi
        for ((i=0;i<$user_num;i++))
        do
        cd 189cloud
        python3 189cloud.py --username ${user_list[$i]} --password ${pwd_list[$i]}
        done
