name: 联通营业厅签到领积分

on:
  workflow_dispatch:
  # push:
  #   branches: 
  #     - master
  # watch:
  #   types: started
  schedule:
    - cron: 15 22 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: "签入仓库"
        uses: actions/checkout@v2

      - name: "初始化Python"
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
          
      - name: "安装依赖包"
        run: |
          cd cn_unicom
          pip install -r requirements.txt

      - name: "运行 联通营业厅签到领积分"
        env:
           cookie: ${{ secrets.CN_UNICOM_COOKIE }}
        run: |
          cd cn_unicom
          python3 cn_unicom.py ${cookie}
          