name: 联通营业厅签到领积分

on:
  workflow_dispatch:
  # push:
  #   branches: 
  #     - master
  # watch:
  #   types: started
  schedule:
    - cron: 15 22 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: "签入仓库"
        uses: actions/checkout@v2

      - name: 运行时间
        run: |
          time=$(curl -s "http://quan.suning.com/getSysTime.do")
          echo -e "当前时间：\n${time}"

      - name: 运行时间
        run: |
          time=$(curl -s "http://quan.suning.com/getSysTime.do")
          echo -e "当前时间：\n${time}"
           
    #设置PARAMETER的值为脚本支持的参数,如 membercenter 13800008888@112233 18388880000@123456
 
      - name: 运行号码签到
        env:
          PARAMETER: ${{ secrets.CN_UNICOM_COOKIE }}
        run: |
          cd cn_unicom
          bash CnUnicom.sh $PARAMETER
          