name: 爱奇艺会员签到

on:
  workflow_dispatch:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
#   watch:
#     types: [started]
  schedule:
    - cron: "*/20 16 * * *"

jobs:
  build:
      runs-on: ubuntu-latest
      if: github.event.repository.owner.id == github.event.sender.id
      steps:
          - name: "签入仓库"
            uses: actions/checkout@v2
          - name: Use Node.js 10.x
            uses: actions/setup-node@v1
            with:
              node-version: 10.x
          - name: npm install
            run: |
              cd iqiyi
              npm install
          - name: "运行 爱奇艺会员签到"
            run: |
              node function/iqiyi.js
          env:
            iQIYI_COOKIE: ${{ secrets.iQIYI_COOKIE }}
            SEND_KEY: ${{ secrets.SEND_KEY }}
            PUSH_KEY: ${{ secrets.SCKEY  }}
            BARK_PUSH: ${{ secrets.BARK_PUSH }}
            QQ_SKEY: ${{ secrets.QQ_SKEY}}
            QQ_MODE: ${{ secrets.QQ_MODE}}
            PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN}}
            PUSH_PLUS_USER: ${{ secrets.PUSH_PLUS_USER}}
            QYWX_KEY: ${{ secrets.QYWX_KEY}}
            QYWX_AM: ${{ secrets.QYWX_AM}}
            TG_PROXY_HOST: ${{ secrets.TG_PROXY_HOST}}
            TG_PROXY_PORT: ${{ secrets.TG_PROXY_PORT}}
            IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY}}
            TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
            TG_USER_ID: ${{ secrets.TG_USER_ID }}
            BARK_SOUND: ${{ secrets.BARK_SOUND }}
            DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
            DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
