name: 小米刷步数

on:
  workflow_dispatch:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]
  schedule:
    - cron: 0 10 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: "签入仓库"
        uses: actions/checkout@v2

      - name: "初始化Python"
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
          
      - name: "运行 小米刷步数"
        run: |
          cd mistep
          pip install requests
          sckey='${{ secrets.SCKEY }}'
          user='${{ secrets.MI_USER }}'
          pwd='${{ secrets.MI_PWD }}'
          step='${{ secrets.MI_STEP }}'
          
          user_list=()
          pwd_list=()
          sckey_list=()
          step_list=()
          IFS="#"
          
          for u in ${user[*]}
          do
          user_list[${#user_list[*]}]=${u}
          done
          
          for p in ${pwd[*]}
          do
          pwd_list[${#pwd_list[*]}]=${p}
          done

          for t in ${step[*]}
          do
          step_list[${#step_list[*]}]=${t}
          done
          
          user_num=${#user_list[*]}
          pwd_num=${#pwd_list[*]}
              
          if [ $user_num != $pwd_num ];then
          echo "账号和密码个数不对应"
          exit 1
          else
          echo "共有 $user_num 个账号，即将开始签到"
          fi
          for ((i=0;i<$user_num;i++))
          do
          python3 xiaomi_steps.py --username ${user_list[$i]} --password ${pwd_list[$i]} --steps ${step_list[$i]} --pushkey ${sckey}
          EOF
          done
          # python3 xiaomi_steps.py <<EOF
          # ${sckey}
          # ${pwd_list}
          # ${pwd_list}
          # ${step_list}
          # EOF
