name: 刷步数

on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]
  schedule:
    - cron: 0 10 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v2
    - name: 初始化Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: 开始
      run: |
        cd mistep
        pip install requests
        sckey='${{ secrets.MI_SCKEY }}'
        user='${{ secrets.MI_USER }}'
        pwd='${{ secrets.MI_PWD }}'
        step='${{ secrets.MI_STEP }}'
        
        python3 xiaomi_steps.py <<EOF
        ${sckey}
        ${user}
        ${pwd}
        ${step}
        EOF
