name: 小米刷步数

on:
  workflow_dispatch:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
#   watch:
#     types: [started]
  schedule:
    - cron: 0 10 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: "签入仓库"
        uses: actions/checkout@v2

      - name: "初始化Python"
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
          
      - name: "运行 小米刷步数"
        run: |
          cd mistep
          pip install requests
          
          pmode=off
          pkey='${{ secrets.PKEY }}'
          user='${{ secrets.MI_USER }}'
          pwd='${{ secrets.MI_PWD }}'
          step='${{ secrets.MI_STEP }}'
          python3 xiaomi_steps.py ${pmode} ${pkey} ${user} ${pwd} ${step}