name: WPS自动邀请

on:
  workflow_dispatch:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
#   watch:
#     types: [started]
  schedule:
    - cron: "45 23,1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: "签入仓库"
        uses: actions/checkout@v2

      - name: "初始化Python"
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: "安装依赖包"
        run: |
          cd wps
          pip install -r requirements.txt

      - name: "运行 WPS自动邀请"
        run: |
          cd wps
          python3 wps_invitation.py
        env:
          WPS_KEY: ${{ secrets.WPS_KEY }}
          SEND_KEY: ${{ secrets.SEND_KEY }}
          PUSH_KEY: ${{ secrets.SCKEY  }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          QQ_SKEY: ${{ secrets.QQ_SKEY}}
          QQ_MODE: ${{ secrets.QQ_MODE}}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
          QYWX_AM: ${{ secrets.QYWX_AM}}
          Orc_Id: ${{ secrets.WPS_OCR_ID}}
          Orc_Secret: ${{ secrets.WPS_OCR_SECRET}}
          
